<a href="https://colab.research.google.com/github/MarcoE25/Clases-Analisis-Datos/blob/main/Clase_1_intermedio_202508.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Esta es una celda de texto, nos sirve para ir armando nuestro apunte de programación

---

# Créditos bancarios para empresas

* INFORMACIÓN SIMULADA
* Nombres de empresas
* USD, EUR, MXN
* Monto de sus créditos ficticios
* Fecha inicio
* Fecha fin

---

Proceso del analista de datos:

* Leer/Extraer la info
* Exploración/LIMPIEZA de datos
* BBDD
* Reportes: power point-PDF, Power BI / Tableu

In [ ]:
import pandas as pd

df_bank = pd.read_csv("https://cursopypagina.github.io/CursoPy/Clase_1.csv")

# head(n): mostrarte las primeras n filas
# Explorar un poco la naturaleza de nuestros datos
df_bank.head()

,Nombre_Empresa,Monto_Credito,Divisa,Operacion,Fecha_Inicio,Fecha_Fin,Plazo
0,grupo bimbo,4117589.71,MXN,OP-100000,27-Aug-2019,"April 24, 2023",1336.0
1,WALMART DE MÉXICO,7008028.47,USD,OP-100001,2017-04-10,18/02/2022,1775.0
2,liverpool,9918174.32,EUR,OP-100002,"April 21, 2017",NaN,NaN
3,grupo lala,1293043.34,USD,OP-100003,24-Nov-2023,NaN,NaN
4,FEMSA,7128647.73,EUR,OP-100004,2024-10-30,NaN,NaN

* ``"2025-01-01"``: string (contiene fecha)
* ``datetime/timestamp``: objetos fechas, son fechas que Python interpreta

In [ ]:
from dateutil import parser
# aaaa-mm-dd
#                   aaaa,mm, dd
# datetime.datetime(2025, 1, 12, 0, 0)
print(parser.parse("01/12/2025"))
print(parser.parse("April 21, 2017"))

2025-01-12 00:00:00
2017-04-21 00:00:00

Objetivo: unificar las columnas de fecha

* utilizaremos la función parse
* funciones lambda-apply

### Funciones lambda

* Funciones anónimas
* Definir funciones por el usuario con una notación más simplificada
* Conviene cuando son tareas rápidas-cortas
* No conviente cuando quieres implementar tareas robustas
* No puedes colocar documentación

Esqueleto para crear una función en Python

```python
def nombreFuncion(param_1, param_2, ....):
  # tarea a realizar
  # instruccion de retorno (opcional)
  return
```

Esqueleto para funciones lambda

```python
nombreFuncion = lambda param_1, param_2, ...: tarea a realizar de la funcion - <return>
```

Función anónima:

* Función lambda sin nombre

```python
lambda param_1, param_2, ...: tarea a realizar de la funcion - <return>
```

In [ ]:
def f(x):
  """
  Documentacion de la funcion:
  * ¿que hace tu funcion?
  * ¿que necesita? Parametros
  * ¿Que regresa?
  * Reglas
  """
  return x ** 2

In [ ]:
# lambda x: x ** 2 ---> funcion anonima
fl = lambda x: x ** 2

In [ ]:
print(f(4))
print(fl(4))

16
16

In [ ]:
# help(fun)
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

### Función apply de pandas 🐼

* Aplica una función, idealmente anónima, a cada elemento/fila de una columna

In [ ]:
# 1. Acceder a la columna de interes
# Fecha_Inicio
df_bank["Fecha_Inicio"] = df_bank["Fecha_Inicio"].apply(lambda x: parser.parse(x))

# fillna(X): te rellena los valores faltantes de la columna de interes
# con el valor X
df_bank["Fecha_Fin"] = df_bank["Fecha_Fin"].fillna("1900-01-01")
df_bank["Fecha_Fin"] = df_bank["Fecha_Fin"].apply(lambda x: parser.parse(x))

In [ ]:
df_bank["Plazo"] = df_bank["Plazo"].fillna(0)

In [ ]:
# te da el tipo de dato de tus columnas
# cuantos nulos por columnas tienes
df_bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Nombre_Empresa  10000 non-null  object
 1   Monto_Credito   10000 non-null  float64
 2   Divisa          10000 non-null  object
 3   Operacion       10000 non-null  object
 4   Fecha_Inicio    10000 non-null  datetime64[ns]
 5   Fecha_Fin       10000 non-null  datetime64[ns]
 6   Plazo           10000 non-null  float64
dtypes: datetime64[ns](2), float64(2), object(3)
memory usage: 547.0+ KB

In [ ]:
# conversion de tipos de datos astype(nuevoTipoDeDatos)
df_bank["Plazo"] = df_bank["Plazo"].astype(int)

In [ ]:
df_bank.head(8)

,Nombre_Empresa,Monto_Credito,Divisa,Operacion,Fecha_Inicio,Fecha_Fin,Plazo
0,grupo bimbo,4117589.71,MXN,OP-100000,2019-08-27,2023-04-24,1336
1,WALMART DE MÉXICO,7008028.47,USD,OP-100001,2017-04-10,2022-02-18,1775
2,liverpool,9918174.32,EUR,OP-100002,2017-04-21,1900-01-01,0
3,grupo lala,1293043.34,USD,OP-100003,2023-11-24,1900-01-01,0
4,FEMSA,7128647.73,EUR,OP-100004,2024-10-30,1900-01-01,0
5,GRUPO LALA,7674495.46,MXN,OP-100005,2024-12-09,1900-01-01,0
6,GRUPO CARSO,3510602.43,EUR,OP-100006,2020-05-30,1900-01-01,0
7,PEMEX,7757624.86,EUR,OP-100007,2019-11-22,1900-01-01,0

In [ ]:
# head(): las 5 primeras filas
# tail(n): te muestralas ultimas n filas
df_bank.tail(10)

,Nombre_Empresa,Monto_Credito,Divisa,Operacion,Fecha_Inicio,Fecha_Fin,Plazo
9990,ALSEA,2184484.70,USD,OP-109990,2023-05-04,"September 14, 2024",499.0
9991,pemex,2142570.09,EUR,OP-109991,06-Sep-2018,2023-02-23,1631.0
9992,pemex,5741285.25,USD,OP-109992,21-Aug-2025,NaN,NaN
9993,LIVERPOOL,3755251.09,USD,OP-109993,08-Oct-2019,2023-05-24,1324.0
9994,GRUPO LALA,5262127.94,MXN,OP-109994,"January 31, 2018",2021-02-12,1108.0
9995,BBVA MÉXICO,7649613.74,MXN,OP-109995,02-Jan-2021,"March 01, 2023",788.0
9996,SORIANA,1578366.47,MXN,OP-109996,28/02/2017,12-Feb-2022,1810.0
9997,walmart de méxico,2057031.71,MXN,OP-109997,2020-05-19,NaN,NaN
9998,GRUPO BIMBO,6555258.51,MXN,OP-109998,13/05/2017,2019-12-24,955.0
9999,soriana,1394502.18,USD,OP-109999,18/05/2024,30/10/2024,165.0

# Formulario-Resumen: Limpieza de datos

## 🐼 Maestro en Pandas🐼
1. ``pd.read_csv("nombreDelArchivo")``: leer el archivo csvy lo convierte a una tabla de pandas (_dataframe_).
2. ``head(n)``: si no le pones parámetros, entonces por defecto se muestran las primeras 5 filas, caso contrario, se muestran las primeras $n$
3. ``tail(n)``: si no le pones parámetros, entonces por defecto se muestran las últimas 5 filas, caso contrario, se muestran las últimas $n$
4. ``apply(nombreFuncion)``: $g\circ f$. Es una función de 🐼 pandas que aplica otra función a cada fila de una columna de un dataframe

---

1. Función lambda: Es una función definida por el usuario que tiene una notación simplificada, ideal para tareas pequeñas, e implícitamente tiene la instrucción de ``return`` implementanda

```python
nombreFuncion = lambda param_1, param_2, . . . : tarea a realizar-<return>
```

2. Función anónima: Es una función lambda sin nombre.

```python
lambda param_1, param_2, . . . : tarea a realizar-<return>
```

---

1. Una vez que ya leiste la información, lo que sigue es explorar los datos y/o realizar limpieza de datos
2. ¿Qué haremos la siguiente clase? Automatizaciones, columans calculadas, filtros, group by, gráficos, joins